In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

colname = ['X-coordinate', 'Y-coordinate', 'Time stamp', 'Button status', 'Azimuth', 'Altitude', 'Pressure']
signDF = pd.read_csv("/home/cp/Documents/DMML/Task2/U1S1.TXT", delimiter = ' ', skiprows = [0])
signDF.columns = colname

In [8]:
signDF.head()

X-coordinate  Y-coordinate  Time stamp  Button status  Azimuth  Altitude  \
0          2933          5678    31275785              1     1480       770   
1          3001          5851    31275795              1     1350       830   
2          3114          6139    31275805              1     1350       800   
3          3217          6198    31275815              1     1350       800   
4          3329          6213    31275825              1     1350       800   

   Pressure  
0       420  
1       433  
2       422  
3       415  
4       423

In [12]:
X = signDF[['X-coordinate']]
Y = signDF[['Y-coordinate']]
P = signDF[['Pressure']]

In [19]:
print(X.head())
print('\t')
print(Y.head())
print('\t')
print(P.head())


   X-coordinate
0          2933
1          3001
2          3114
3          3217
4          3329
	
   Y-coordinate
0          5678
1          5851
2          6139
3          6198
4          6213
	
   Pressure
0       420
1       433
2       422
3       415
4       423


Extracting the columns and converting them to arrays:

In [40]:
X1 = X.to_numpy()
Y1 = Y.to_numpy()
P1 = P.to_numpy()

In [59]:
# Another method:
X2 = np.array(X)

In [60]:
X2[0:10]

array([[2933],
       [3001],
       [3114],
       [3217],
       [3329],
       [3447],
       [3542],
       [3617],
       [3678],
       [3733]])

In [61]:
print(X2[0:10])
print('\n')
print(len(X2))

[[2933]
 [3001]
 [3114]
 [3217]
 [3329]
 [3447]
 [3542]
 [3617]
 [3678]
 [3733]]


83


In [48]:
print(X1[1])
print(len(X1))

[3001]
83


In [64]:
# Calculating the difference vector:

delX = [X1[i]-X1[i-1] for i in range(1,len(X1))]
delY = [Y1[i]-Y1[i-1] for i in range(1,len(Y1))]
delP = [P1[i]-P1[i-1] for i in range(1,len(P1))]

In [65]:
print(delX[0:10])
print('\n')
print(delY[0:10])
print('\n')
print(delP[0:10])

[array([68]), array([113]), array([103]), array([112]), array([118]), array([95]), array([75]), array([61]), array([55]), array([39])]


[array([173]), array([288]), array([59]), array([15]), array([-14]), array([-23]), array([-52]), array([-71]), array([-193]), array([-313])]


[array([13]), array([-11]), array([-7]), array([8]), array([16]), array([52]), array([70]), array([52]), array([25]), array([12])]


In [69]:
## Min-Max normalization without sklearn:

dXmm = [(delX[j] - min(delX))/(max(delX) - min(delX)) for j in range(0,len(delX))]
dYmm = [(delY[j] - min(delY))/(max(delY) - min(delY)) for j in range(0,len(delY))]
dPmm = [(delP[j] - min(delP))/(max(delP) - min(delP)) for j in range(0,len(delP))]

In [71]:
dYmm[0:10]

[array([0.29058908]),
 array([0.33189655]),
 array([0.2496408]),
 array([0.23383621]),
 array([0.22341954]),
 array([0.22018678]),
 array([0.20977011]),
 array([0.2029454]),
 array([0.15912356]),
 array([0.11602011])]

In [73]:
# np.mean(delX)
# np.mean(X)

X-coordinate    5474.73494
dtype: float64

In [74]:
## Z-score normalization using numpy

dXz = [(delX[k] - np.mean(delX))/np.std(delX) for k in range(0,len(delX))]
dYz = [(delY[k] - np.mean(delY))/np.std(delY) for k in range(0,len(delY))]
dPz = [(delP[k] - np.mean(delP))/np.std(delP) for k in range(0,len(delP))]

In [75]:
print(dYz[0:10])

[array([0.46713923]), array([0.77332696]), array([0.163614]), array([0.04646391]), array([-0.03074865]), array([-0.05471117]), array([-0.13192373]), array([-0.18251127]), array([-0.50733651]), array([-0.82683675])]
