In [63]:
import numpy as np
import pandas as pd
from sklearn import neighbors, preprocessing
from sklearn.model_selection import cross_validate
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [17]:
colnames = ['Code','ClumpThk', 'CellSize', 'CellShape', 'Adhesion', 'Epithelial', 'Nuclei', 'Chromatin', 'Nucleoli', 'Mitoses', 'Class']
df = pd.read_csv('/home/cp/Documents/DMML/BreastCancerWisconsin/breast-cancer-wisconsin.data', names=colnames)

In [18]:
df.head()

Code  ClumpThk  CellSize  CellShape  Adhesion  Epithelial Nuclei  \
0  1000025         5         1          1         1           2      1   
1  1002945         5         4          4         5           7     10   
2  1015425         3         1          1         1           2      2   
3  1016277         6         8          8         1           3      4   
4  1017023         4         1          1         3           2      1   

   Chromatin  Nucleoli  Mitoses  Class  
0          3         1        1      2  
1          3         2        1      2  
2          3         1        1      2  
3          3         7        1      2  
4          3         1        1      2

In [19]:
df.drop(['Code'], axis=1, inplace=True)

In [20]:
df.replace('?',-9999, inplace=True)

In [29]:
# get attributes and classes in place
X = np.array(df.drop(['Class'], axis=1))
y = np.array(df['Class'])

In [32]:
# split data into training and testing sections
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)


In [59]:
knn3 = neighbors.KNeighborsClassifier(n_neighbors = 3)
knn5 = neighbors.KNeighborsClassifier(n_neighbors = 5)
knn7 = neighbors.KNeighborsClassifier(n_neighbors = 7)
knn9 = neighbors.KNeighborsClassifier(n_neighbors = 9)
knn12 = neighbors.KNeighborsClassifier(n_neighbors = 12)
knn15 = neighbors.KNeighborsClassifier(n_neighbors = 15)
knn18 = neighbors.KNeighborsClassifier(n_neighbors = 18)

In [60]:
knn3.fit(X_train, y_train)
knn5.fit(X_train, y_train)
knn7.fit(X_train, y_train)
knn9.fit(X_train, y_train)
knn12.fit(X_train, y_train)
knn15.fit(X_train, y_train)
knn18.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=18, p=2,
                     weights='uniform')

In [77]:
accuracy3 = knn3.score(X_test, y_test)
print("Accuracy when neighbors = 3:",accuracy3*100)
accuracy5 = knn5.score(X_test, y_test)
print("Accuracy when neighbors = 5:",accuracy5*100)
accuracy7 = knn7.score(X_test, y_test)
print("Accuracy when neighbors = 7:",accuracy7*100)
accuracy9 = knn9.score(X_test, y_test)
print("Accuracy when neighbors = 9:",accuracy9*100)
accuracy12 = knn12.score(X_test, y_test)
print("Accuracy when neighbors = 12:",accuracy12*100)
accuracy15 = knn15.score(X_test, y_test)
print("Accuracy when neighbors = 15:",accuracy15*100)


Accuracy when neighbors = 3: 97.85714285714285
Accuracy when neighbors = 5: 97.85714285714285
Accuracy when neighbors = 7: 97.14285714285714
Accuracy when neighbors = 9: 97.14285714285714
Accuracy when neighbors = 12: 97.85714285714285
Accuracy when neighbors = 15: 97.85714285714285


In [81]:
y_pred3 = knn3.predict(X_test)
y_pred5 = knn5.predict(X_test)
y_pred7 = knn7.predict(X_test)
y_pred9 = knn9.predict(X_test)
y_pred12 = knn12.predict(X_test)
y_pred15 = knn15.predict(X_test)

## Making new prediction##

In [82]:
print("Enter the parameters: 'ClumpThk', 'CellSize', 'CellShape', 'Adhesion', 'Epithelial', 'Nuclei', 'Chromatin', 'Nucleoli', 'Mitoses' ")


Enter the parameters: 'ClumpThk', 'CellSize', 'CellShape', 'Adhesion', 'Epithelial', 'Nuclei', 'Chromatin', 'Nucleoli', 'Mitoses' 


In [83]:
new_tests = np.array([[10, 10, 2, 3, 10, 2, 1, 8, 44], [10, 1, 12, 3, 1, 12, 1, 8, 12], [3, 1, 1, 3, 1, 12, 1, 2, 1]])
#new_tests = new_tests.reshape(len(new_tests),-1)

In [84]:
new_tests

array([[10, 10,  2,  3, 10,  2,  1,  8, 44],
       [10,  1, 12,  3,  1, 12,  1,  8, 12],
       [ 3,  1,  1,  3,  1, 12,  1,  2,  1]])

In [85]:
pred3 = knn3.predict(new_tests)
pred5 = knn5.predict(new_tests)
pred7 = knn7.predict(new_tests)
pred9 = knn9.predict(new_tests)
pred12 = knn12.predict(new_tests)
pred15 = knn15.predict(new_tests)

In [86]:
#Accuracy:
#print("Accuracy: ", accuracy)

prediction5.shape

(140,)

In [87]:
#Prediction
for P in prediction:
    if P == 2:
        print("Benign")
    else:
        print("Malignant")

Malignant
Malignant
Benign


In [88]:
#Confusin Matrix
CM3 = confusion_matrix(y_test, y_pred3)
CM5 = confusion_matrix(y_test, y_pred5)
CM7 = confusion_matrix(y_test, y_pred7)
CM9 = confusion_matrix(y_test, y_pred9)
CM12 = confusion_matrix(y_test, y_pred12)
CM15 = confusion_matrix(y_test, y_pred15)

print("Confusion Matrix for 3NN:\n",CM3)
print("Confusion Matrix for 5NN:\n",CM5)
print("Confusion Matrix for 7NN:\n",CM7)
print("Confusion Matrix for 9NN:\n",CM9)
print("Confusion Matrix for 12NN:\n",CM12)
print("Confusion Matrix for 15NN:\n",CM15)

Confusion Matrix for 3NN:
 [[86  2]
 [ 1 51]]
Confusion Matrix for 5NN:
 [[86  2]
 [ 1 51]]
Confusion Matrix for 7NN:
 [[86  2]
 [ 2 50]]
Confusion Matrix for 9NN:
 [[86  2]
 [ 2 50]]
Confusion Matrix for 12NN:
 [[86  2]
 [ 1 51]]
Confusion Matrix for 15NN:
 [[86  2]
 [ 1 51]]
